import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by SilvesterSpath',
  keywords: 'nextjs, react, typescript',
};

const HomePage = () => {
  return (
    <main className='flex min-h-screen flex-col items-center justify-between p-24'>
      <h1 className='text-3xl'>Welcome</h1>
      <Link href='/properties'>Show Properties</Link>
    </main>
  );
};

export default HomePage;
